name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '52 18 * * 2'

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        mod: [potentiamod]
        # mod: [potentiamod, penguinmod EXPERIMENTAL-gaiamod]
    name: "build: ${{ matrix.mod }}"
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Checkout self
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Checkout scratch-gui
      uses: actions/checkout@v4
      with:
        repository: ${{ (matrix.mod == 'potentiamod' && 'PotentiaMod/scratch-gui') || matrix.mod == 'penguinmod' && 'PenguinMod/penguinmod.github.io') || 'GaiaMod-Main/gaiamod-main.github.io' }}
        path: scratch-gui
    - name: Checkout PotentiaMod extensions
      uses: actions/checkout@v4
      with:
        repository: PotentiaMod/extensions
        path: extensions
    - name: Build GUI
      run: |
        cd scratch-gui
        npm ci
        NODE_ENV=production ROUTING_STYLE=hash npm run build
        cd ..
    - name: Patch
      run: python3 patch.py
    - name: Bundle into single file
      run: |
        node patch_singlefile.mjs
        node patch_singlefile.mjs --extensions
    - name: Rename files to match mod
      run: |
        mv pot-standalone.html ${{ matrix.mod }}-standalone.html
        mv pot-standalone-offline-extensions.html ${{ matrix.mod }}-standalone-offline-extensions.html
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.mod }}-standalone
        path: ${{ matrix.mod }}-standalone.html
    - name: Upload extensions artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.mod }}-standalone-offline-extensions
        path: ${{ matrix.mod }}-standalone-offline-extensions.html
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: build
        github_token: ${{ github.token }}
    - name: Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: Standalone PotentiaMod Build
        tag_name: build
        body: |
          Download the `pot-standalone.html` file below and open it in your browser to use PotentiaMod.
          Still very experimental, not all things will work properly.
          By default, unsandboxed PotentiaMod extensions are still fetched from potentiamod.github.io/extensions. Use `pot-standalone-offline-extensions.html` instead for the extensions themselves to work offline, but documentation pages, extension example files, sample projects and the standalone library page (not the one in the editor) will still only be online.
          This download updates weekly (apparently at 18:52, idk the timezone, on Tuesdays).
        files: "*.*"
        make_latest: true
        fail_on_unmatched_files: true
